# roles/init-chain/tasks/init_priv_rpc.yml

- name: Ensure correct ownership on /opt/primea (after snapshot)
  file:
    path: /opt/primea
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes

- name: Pull latest PrimeaChain repo (in case of genesis updates)
  git:
    repo: git@github.com:primeanetwork/primeachain.git
    dest: /opt/primea/primeachain
    version: main
    force: yes
    accept_hostkey: yes
    key_file: /home/{{ ansible_user }}/.ssh/github_id_rsa
  become: false

- name: Verify testnet genesis file exists
  stat:
    path: /opt/primea/primeachain/ansible/files/testnet-genesis.json
  register: genesis_file

- name: Fail if genesis file is missing
  fail:
    msg: "testnet-genesis.json not found"
  when: not genesis_file.stat.exists
- name: Delete previous chain data
  file:
    path: /opt/primea/primeachain/bsc-core/data
    state: absent
  become: yes
  become_user: superuser

- name: Initialize Geth with testnet genesis
  shell: |
    export PATH=/usr/local/go/bin:$PATH
    /opt/primea/primeachain/bsc-core/build/bin/geth init \
      --datadir=/opt/primea/primeachain/bsc-core/data \
      /opt/primea/primeachain/ansible/files/testnet-genesis.json
  args:
    chdir: /opt/primea/primeachain/bsc-core
  become: yes
  become_user: superuser

- name: Check if chain was initialized
  stat:
    path: /opt/primea/primeachain/bsc-core/data/geth
  register: chain_data_check

- name: Fail if Geth chain was not initialized properly
  fail:
    msg: "Geth data directory was not created. Init failed."
  when: not chain_data_check.stat.exists

- name: ✅ Geth initialization successful
  debug:
    msg: "✅ Geth testnet chain initialized on {{ inventory_hostname }}."

- name: Print Genesis Block Hash
  command: >
    /opt/primea/primeachain/bsc-core/build/bin/geth
    inspect /opt/primea/primeachain/bsc-core/testnet-genesis.json
  register: genesis_inspect
  changed_when: false
  ignore_errors: true

- name: Display Genesis Hash
  debug:
    msg: "Genesis Hash for {{ inventory_hostname }}: {{ genesis_inspect.stdout }}"

- name: Ensure superuser owns all Geth directories after init
  file:
    path: /opt/primea/primeachain/bsc-core
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes

