---
# Inject static-nodes and wallet key into validators + restart

- name: Ensure required ports are open on validator nodes
  become: yes
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - { port: 30303, proto: "tcp" }
    - { port: 30303, proto: "udp" }
  loop_control:
    label: "{{ item.port }}/{{ item.proto }}"
  when: "'validator_nodes' in group_names"

- name: Read all enode files from artifacts directory
  delegate_to: localhost
  find:
    paths: "{{ playbook_dir }}/artifacts/phase5"
    patterns: "*.enode"
  register: enode_files

- name: Load enode contents into a list
  delegate_to: localhost
  slurp:
    src: "{{ item.path }}"
  loop: "{{ enode_files.files }}"
  register: enode_raw_list

- name: Read enode file contents
  delegate_to: localhost
  slurp:
    src: "{{ item.path }}"
  with_items: "{{ enode_files.files }}"
  register: slurped_enodes

- name: Set enode list fact
  delegate_to: localhost
  set_fact:
    enode_list: "{{ slurped_enodes.results | map(attribute='content') | map('b64decode') | list }}"

- name: Inject static-nodes.json
  copy:
    dest: /opt/primea/primeachain/bsc-core/data/geth/static-nodes.json
    content: "{{ enode_list | to_nice_json }}"
    mode: '0644'

- name: Decode enodes into a list
  set_fact:
    all_enodes: "{{ enode_raw_list.results | map(attribute='content') | map('b64decode') | list }}"

- name: Join all enodes into bootnodes string
  set_fact:
    bootnodes_line: "--bootnodes={{ all_enodes | join(',') }}"

- name: Set service name for validator
  set_fact:
    geth_service_name: "geth-validator"

- name: Determine full validator key filename and unlock info
  set_fact:
    validator_metadata: >-
      {{
        {
          'validator-1': {
            'keyfile': 'UTC--2025-02-20T09-07-16.273603895Z--c79de6a1eefaa4325b71590585b4b056b0750e97',
            'address': 'c79de6a1eefaa4325b71590585b4b056b0750e97',
            'password': 'Rhbsm93**primeavalidator1'
          },
          'validator-2': {
            'keyfile': 'UTC--2025-02-20T09-07-40.434141001Z--ceb07760b2b9797b7e31cfd648f7302925c28d58',
            'address': 'ceb07760b2b9797b7e31cfd648f7302925c28d58',
            'password': 'Rhbsm93**primeavalidator2'
          },
          'validator-3': {
            'keyfile': 'UTC--2025-02-20T09-08-00.773404193Z--2c1eb859b739829ea7d3b99f4445710efbed2017',
            'address': '2c1eb859b739829ea7d3b99f4445710efbed2017',
            'password': 'Rhbsm93**primeavalidator3'
          }
        }[inventory_hostname]
      }}

- name: Ensure keystore directory exists
  file:
    path: /opt/primea/primeachain/bsc-core/data/keystore
    state: directory
    mode: '0700'
    owner: superuser
    group: superuser

- name: Copy validator key file into node keystore
  copy:
    src: "{{ playbook_dir }}/files/keys/{{ validator_metadata.keyfile }}"
    dest: "/opt/primea/primeachain/bsc-core/data/keystore/"
    owner: superuser
    group: superuser
    mode: '0600'

- name: Create password file securely on remote node
  copy:
    content: "{{ validator_metadata.password }}"
    dest: "/opt/primea/primeachain/bsc-core/password.txt"
    owner: superuser
    group: superuser
    mode: '0600'

- name: Backup current systemd unit file for safety
  copy:
    src: "/etc/systemd/system/{{ geth_service_name }}.service"
    dest: "/etc/systemd/system/{{ geth_service_name }}.service.backup"
    remote_src: true
    force: yes

- name: Inject bootnodes above --nat
  lineinfile:
    path: "/etc/systemd/system/{{ geth_service_name }}.service"
    insertbefore: '^\s*--nat\s'
    line: "  {{ bootnodes_line }} \\"
    state: present

- name: Inject unlock above --nat
  lineinfile:
    path: "/etc/systemd/system/{{ geth_service_name }}.service"
    insertbefore: '^\s*--nat\s'
    line: "  --unlock={{ validator_metadata.address }} \\"
    state: present
    
- name: Inject password above --nat
  lineinfile:
    path: "/etc/systemd/system/{{ geth_service_name }}.service"
    insertbefore: '^\s*--nat\s'
    line: "  --password=/opt/primea/primeachain/bsc-core/password.txt \\"
    state: present
    
- name: Inject allow-insecure-unlock above --nat
  lineinfile:
    path: "/etc/systemd/system/{{ geth_service_name }}.service"
    insertbefore: '^\s*--nat\s'
    line: "  --allow-insecure-unlock \\"
    state: present
    
- name: Reload systemd daemons
  shell: |
    systemctl daemon-reload
    systemctl daemon-reexec

- name: Enable and start Geth service
  systemd:
    name: "{{ geth_service_name }}"
    enabled: true
    state: started

- name: Wait 15 seconds after starting Geth
  pause:
    seconds: 15

- name: Check if Geth process is running
  shell: pgrep -f '/opt/primea/primeachain/bsc-core/build/bin/geth --datadir'
  register: geth_status
  failed_when: geth_status.rc != 0
  changed_when: false

- name: Confirm Geth started successfully
  debug:
    msg: "Geth is running with PID(s): {{ geth_status.stdout_lines }}"
