# roles/peering/tasks/pull_enodes.yml

- name: Create local directory for enode results
  delegate_to: localhost
  run_once: true
  file:
    path: "{{ playbook_dir }}/artifacts/phase5"
    state: directory
    mode: '0755'

- name: Extract enode from running Geth node
  shell: >
    echo "admin.nodeInfo.enode" |
    /opt/primea/primeachain/bsc-core/build/bin/geth attach /opt/primea/primeachain/bsc-core/data/geth.ipc |
    grep -oE 'enode://[^"]+'
  register: enode_result
  changed_when: false
  failed_when: enode_result.rc != 0 or enode_result.stdout == ""

- name: Save enode for this host to local file
  delegate_to: localhost
  copy:
    dest: "{{ playbook_dir }}/artifacts/phase5/{{ inventory_hostname }}.enode"
    content: "{{ enode_result.stdout }}"

- name: Show enode string
  debug:
    msg: "Host {{ inventory_hostname }} enode: {{ enode_result.stdout }}"

