---
# Phase 2 - Clone and Build Primea Geth Binary

- name: Ensure destination directory exists
  file:
    path: /opt/primea
    state: directory
    owner: superuser
    group: superuser
    mode: '0755'
  become: yes

- name: Clean old PrimeaChain repo if exists
  file:
    path: /opt/primea/primeachain
    state: absent
  become: yes

- name: Clone PrimeaChain repo via SSH using host-forwarded key
  git:
    repo: git@github.com:primeanetwork/primeachain.git
    dest: /opt/primea/primeachain
    version: main
    update: no
    force: yes
  become: yes
  become_user: superuser

- name: Ensure Makefile exists
  stat:
    path: /opt/primea/primeachain/bsc-core/Makefile
  register: makefile_check

- name: Fail if Makefile is missing
  fail:
    msg: "Makefile not found at expected path! Check repo structure."
  when: not makefile_check.stat.exists

- name: Clean previous build artifacts
  command: make clean
  args:
    chdir: /opt/primea/primeachain/bsc-core
  become: yes
  become_user: superuser

- name: Compile geth using make (with Go env loaded)
  shell: |
    export PATH=/usr/local/go/bin:$PATH
    export GOPATH=$HOME/go
    export GOBIN=$GOPATH/bin
    make -j1 geth
  args:
    chdir: /opt/primea/primeachain/bsc-core
  become: yes

- name: Check if geth binary was built
  stat:
    path: /opt/primea/primeachain/bsc-core/build/bin/geth
  register: geth_bin

- name: Fail if geth binary is missing
  fail:
    msg: "geth binary was not built correctly!"
  when: not geth_bin.stat.exists

- name: Check geth version
  shell: |
    export PATH=/usr/local/go/bin:$PATH
    /opt/primea/primeachain/bsc-core/build/bin/geth version
  register: geth_output
  changed_when: false
  become: yes


- name: Print compiled geth version
  debug:
    var: geth_output.stdout_lines
