---
# Server Prepping Role - Main Tasks
# This role prepares Ubuntu servers for Primea blockchain deployment

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Upgrade all packages
  apt:
    upgrade: yes
    autoremove: yes
    autoclean: yes
  become: yes

- name: Remove default golang packages (if installed)
  apt:
    name: golang-go
    state: absent
  become: yes

- name: Install required packages
  apt:
    name:
      - git
      - make
      - curl
      - ufw
      - htop
      - build-essential
    state: present
  become: yes

- name: Download latest Go binary
  get_url:
    url: https://go.dev/dl/go1.21.6.linux-amd64.tar.gz
    dest: /tmp/go.tar.gz
    mode: '0644'
  become: yes

- name: Remove old Go installation
  file:
    path: /usr/local/go
    state: absent
  become: yes

- name: Extract Go archive to /usr/local
  unarchive:
    src: /tmp/go.tar.gz
    dest: /usr/local
    remote_src: yes
  become: yes

- name: Set Go environment variables system-wide
  copy:
    dest: /etc/profile.d/go.sh
    content: |
      export PATH=$PATH:/usr/local/go/bin
      export GOPATH=$HOME/go
      export GOBIN=$GOPATH/bin
    mode: '0755'
    owner: root
    group: root
  become: yes


- name: Ensure Go is in PATH for the current shell
  shell: "source /etc/profile.d/go.sh"
  args:
    executable: /bin/bash

- name: Enable UFW firewall
  ufw:
    state: enabled
    policy: deny
  become: yes

- name: Allow OpenSSH through UFW
  ufw:
    rule: allow
    name: OpenSSH
  become: yes

- name: Set timezone to UTC
  timezone:
    name: Etc/UTC
  become: yes

- name: Create base directory for Primea
  file:
    path: /opt/primea
    state: directory
    owner: superuser
    group: superuser
    mode: '0755'
  become: yes
