- name: Ensure no stray Geth processes before starting
  shell: pkill -f '/opt/primea/primeachain/bsc-core/build/bin/geth'
  register: kill_result
  failed_when: false
  changed_when: false

- name: Stop old geth-validator service (if exists)
  systemd:
    name: geth-validator
    state: stopped
    enabled: false
    force: true
  register: stop_result
  failed_when: false
  changed_when: false

- name: Remove old systemd unit file (if exists)
  file:
    path: /etc/systemd/system/geth-validator.service
    state: absent

- name: Determine NAT external IP based on hostname
  set_fact:
    node_nat_ip: >-
      {% if inventory_hostname == 'validator-1' %}192.168.249.4{% elif inventory_hostname == 'validator-2' %}192.168.249.5{% elif inventory_hostname == 'validator-3' %}192.168.249.6{% else %}127.0.0.1{% endif %}

- name: Create systemd service for geth-validator
  copy:
    dest: /etc/systemd/system/geth-validator.service
    content: |
      [Unit]
      Description=Geth Validator Node (PrimeaChain)
      After=network.target

      [Service]
      User=superuser
      WorkingDirectory=/opt/primea/primeachain/bsc-core
      ExecStart=/opt/primea/primeachain/bsc-core/build/bin/geth \
        --datadir /opt/primea/primeachain/bsc-core/data \
        --networkid 1698369 \
        --http \
        --http.addr "0.0.0.0" \
        --http.port 8545 \
        --http.vhosts "*" \
        --http.api "eth,web3,net,admin,miner" \
        --metrics \
        --pprof \
        --nat "extip:{{ node_nat_ip }}"
      Restart=always
      RestartSec=5

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd daemon
  command: systemctl daemon-reexec

- name: Enable and start geth-validator service
  systemd:
    name: geth-validator
    enabled: true
    state: started

- name: Wait 15 seconds after starting Geth
  pause:
    seconds: 15

- name: Check if Geth process is running
  shell: pgrep -f '/opt/primea/primeachain/bsc-core/build/bin/geth --datadir'
  register: geth_status
  failed_when: geth_status.rc != 0
  changed_when: false

- name: Confirm Geth started successfully
  debug:
    msg: "Geth is running with PID(s): {{ geth_status.stdout_lines }}"

