---
# Phase 5 - Pull enodes from all Geth nodes (RPC + validators)

- name: Phase 5 - Collect enodes from all nodes
  hosts:
    - public_rpc_nodes
    - private_rpc_nodes
    - validators
  become: yes
  vars:
    ansible_user: superuser
  roles:
    - role: peering
      tasks_from: pull_enodes
