---
# Phase 3 - Initialize the chain on all node types (Public RPC, Private RPC, Validators)

- name: Phase 3 - Initialize Testnet Genesis on Public RPC
  hosts: public_rpc_nodes
  become: yes
  vars:
    ansible_user: superuser
  tasks:
    - name: Include task to initialize geth on public RPC node
      include_tasks: roles/init-chain/tasks/init_pub_rpc.yml

- name: Phase 3 - Initialize Testnet Genesis on Private RPC
  hosts: private_rpc_nodes
  become: yes
  vars:
    ansible_user: superuser
  tasks:
    - name: Include task to initialize geth on private RPC node
      include_tasks: roles/init-chain/tasks/init_priv_rpc.yml

- name: Phase 3 - Initialize Testnet Genesis on Validators
  hosts: validators
  become: yes
  vars:
    ansible_user: superuser
  tasks:
    - name: Include task to initialize geth on validator node
      include_tasks: roles/init-chain/tasks/init_validators.yml
