all:
  vars:
    ansible_user: superuser

  children:
    public_rpc_nodes:
      hosts:
        prim-test-public-rpc:
          ansible_host: 192.168.249.2

    private_rpc_nodes:
      hosts:
        prim-test-private-rpc:
          ansible_host: 192.168.249.3

    validators:
      hosts:
        validator-1:
          ansible_host: 192.168.249.4
        validator-2:
          ansible_host: 192.168.249.5
        validator-3:
          ansible_host: 192.168.249.6
