---
galaxy_info:
  role_name: geth_and_init_genesis
  author: Rodrigo Herrera
  description: Initialize Geth with genesis block and start services
  license: MIT
  min_ansible_version: 2.9

dependencies: []
